const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("🚀 Deploying contracts with:", deployer.address);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("💰 Balance:", ethers.formatEther(balance), "MATIC");

  // Deploy PlaxusIdentity
  console.log("\n📋 Deploying PlaxusIdentity...");
  const Identity = await ethers.getContractFactory("PlaxusIdentity");
  const identity = await Identity.deploy();
  await identity.waitForDeployment();
  const identityAddress = await identity.getAddress();
  console.log("✅ PlaxusIdentity deployed to:", identityAddress);

  // Deploy PlaxusCallRegistry
  console.log("\n📋 Deploying PlaxusCallRegistry...");
  const Registry = await ethers.getContractFactory("PlaxusCallRegistry");
  const registry = await Registry.deploy();
  await registry.waitForDeployment();
  const registryAddress = await registry.getAddress();
  console.log("✅ PlaxusCallRegistry deployed to:", registryAddress);

  // Deploy PlaxusTips
  console.log("\n📋 Deploying PlaxusTips...");
  const Tips = await ethers.getContractFactory("PlaxusTips");
  const tips = await Tips.deploy();
  await tips.waitForDeployment();
  const tipsAddress = await tips.getAddress();
  console.log("✅ PlaxusTips deployed to:", tipsAddress);

  // Save addresses to file
  const addresses = {
    network: "mumbai",
    chainId: 80001,
    deployedAt: new Date().toISOString(),
    deployer: deployer.address,
    contracts: {
      PlaxusIdentity:    identityAddress,
      PlaxusCallRegistry: registryAddress,
      PlaxusTips:        tipsAddress,
    },
    polygonscan: {
      PlaxusIdentity:    `https://mumbai.polygonscan.com/address/${identityAddress}`,
      PlaxusCallRegistry: `https://mumbai.polygonscan.com/address/${registryAddress}`,
      PlaxusTips:        `https://mumbai.polygonscan.com/address/${tipsAddress}`,
    },
  };

  // Save to blockchain folder
  fs.writeFileSync(
    path.join(__dirname, "../deployed-addresses.json"),
    JSON.stringify(addresses, null, 2)
  );

  // Also save to frontend so it can use the addresses
  const frontendPath = path.join(__dirname, "../../frontend/src/lib/contracts.js");
  const frontendContent = `// Auto-generated by deploy script — do not edit manually
export const CONTRACT_ADDRESSES = ${JSON.stringify(addresses.contracts, null, 2)};

export const CHAIN_ID = ${addresses.chainId};

export const POLYGONSCAN_BASE = "https://mumbai.polygonscan.com";
`;
  fs.writeFileSync(frontendPath, frontendContent);

  console.log("\n🎉 All contracts deployed!");
  console.log("📄 Addresses saved to deployed-addresses.json");
  console.log("📄 Frontend contracts.js updated");
  console.log("\n🔍 View on Polygonscan:");
  console.log("  Identity:  ", addresses.polygonscan.PlaxusIdentity);
  console.log("  Registry:  ", addresses.polygonscan.PlaxusCallRegistry);
  console.log("  Tips:      ", addresses.polygonscan.PlaxusTips);

  console.log("\n📌 Next step — verify contracts:");
  console.log(`  npx hardhat verify --network mumbai ${identityAddress}`);
  console.log(`  npx hardhat verify --network mumbai ${registryAddress}`);
  console.log(`  npx hardhat verify --network mumbai ${tipsAddress}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
