// Auto-generated by deploy script — do not edit manually
export const CONTRACT_ADDRESSES = {
  "PlaxusIdentity": "0x3f912556b359b84151050Ee74a0fBdb47Cfbc822",
  "PlaxusCallRegistry": "0x1D7611608834C3bB6f938Cf326d577670c291443",
  "PlaxusTips": "0x0b051FB226E2A0ccC691414e7b1d45b62674c495"
};

export const CHAIN_ID = 80001;

export const POLYGONSCAN_BASE = "https://mumbai.polygonscan.com";
